"""
Tiny builder for Power Apps canvas source (.pa.yaml, schema v3).

Every screen of the portal is described in Python (screens.py) with the helpers
below, then emitted twice from the same objects:
  * app/Src/<Screen>.pa.yaml          -> packed into the .msapp  (Route A)
  * paste/<NN>-<Screen>.yaml          -> "Paste code" into Studio (Route B)

Control type ids
  Pinned versions are the ones a February-2026 Power Apps Studio wrote into
  Microsoft's own test app (PowerApps-Tooling, AlmTestApp-asManyEntitiesAsPossible.msapp).
  Classic input controls are written WITHOUT a version: per Microsoft's pa.yaml
  docs, "If no version is specified, the most current version of the control
  is used", which avoids a paste failing on a version mismatch.
"""
import re

CONTAINER = "GroupContainer@1.4.0"
LABEL = "Label@2.5.1"
RECT = "Rectangle@2.3.0"
IMAGE = "Image@2.2.3"
ICON = "Classic/Icon@2.5.0"
GALLERY = "Gallery@2.15.0"
GALLERY_VARIANT = "BrowseLayout_Vertical_OneTextVariant_ver5.0"
BUTTON = "Classic/Button"
TEXTINPUT = "Classic/TextInput"
DROPDOWN = "Classic/DropDown"
COMBOBOX = "Classic/ComboBox"
DATEPICKER = "Classic/DatePicker"
TIMER = "Timer"
ADDMEDIA = "AddMedia"

MONO = "fMono"
UI = "fUI"

ALL_NAMES = {}


class Ctl:
    def __init__(self, name, ctype, props=None, children=None, variant=None):
        if not re.match(r"^[A-Za-z][A-Za-z0-9_]*$", name):
            raise ValueError("bad control name " + name)
        self.name, self.ctype, self.variant = name, ctype, variant
        self.props = dict(props or {})
        self.children = list(children or [])

    def add(self, *kids):
        for k in kids:
            if isinstance(k, (list, tuple)):
                self.children.extend(k)
            elif k is not None:
                self.children.append(k)
        return self

    def walk(self):
        yield self
        for c in self.children:
            yield from c.walk()


def _fmt(v):
    """Python value -> Power Fx formula text (without the leading '=')."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v) if isinstance(v, float) else str(v)
    return str(v)


def q(s):
    """Python string -> Power Fx text literal."""
    return '"' + str(s).replace('"', '""') + '"'


# ---------------------------------------------------------------- emit
def _scalar(formula):
    f = "=" + formula
    risky = ("\n" in f or ": " in f or " #" in f or f.endswith(":") or f.endswith(" ")
             or "\t" in f or f.startswith("= "))
    return f, risky


def emit_props(props, ind):
    out = []
    for k in sorted(props):   # Studio writes properties alphabetically
        f, risky = _scalar(_fmt(props[k]))
        if risky:
            out.append(" " * ind + k + ": |-")
            for line in f.split("\n"):
                out.append(" " * (ind + 2) + line.rstrip() if line.strip() else "")
        else:
            out.append(" " * ind + k + ": " + f)
    return out


def emit_ctl(c, ind):
    """Emit one control as a sequence item:  - Name:\n    Control: ..."""
    p = " " * ind
    out = [p + "- " + c.name + ":"]
    out.append(p + "    Control: " + c.ctype)
    if c.variant:
        out.append(p + "    Variant: " + c.variant)
    if c.props:
        out.append(p + "    Properties:")
        out += emit_props(c.props, ind + 6)
    if c.children:
        out.append(p + "    Children:")
        for ch in c.children:
            out += emit_ctl(ch, ind + 6)
    return out


HEADER = """# ************************************************************************************************
# JCB EDS Lab Material Portal - Power Apps canvas source (pa.yaml schema v3)
# Generated by tools/build.py from tools/screens.py. Edit the Python, rebuild, do not hand-edit.
# ************************************************************************************************
"""


def emit_screen(name, screen_props, root):
    out = [HEADER.rstrip(), "Screens:", "  " + name + ":"]
    if screen_props:
        out.append("    Properties:")
        out += emit_props(screen_props, 6)
    out.append("    Children:")
    out += emit_ctl(root, 6)
    return "\n".join(out) + "\n"


def emit_paste(root):
    return "\n".join(emit_ctl(root, 0)) + "\n"


def emit_app(props):
    out = [HEADER.rstrip(), "App:", "  Properties:"]
    out += emit_props(props, 4)
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- controls
def box(name, x, y, w, h, kids=None, fill="cPanel", border="cLine", thick=1, auto=False,
        direction="Vertical", gap=0, pad=0, scroll=False, visible=None, extra=None):
    p = {"Fill": fill, "BorderColor": border, "BorderThickness": thick, "DropShadow": "DropShadow.None",
         "RadiusTopLeft": 0, "RadiusTopRight": 0, "RadiusBottomLeft": 0, "RadiusBottomRight": 0}
    if x is not None:
        p.update({"X": x, "Y": y})
    if w is not None:
        p["Width"] = w
    if h is not None:
        p["Height"] = h
    if auto:
        p.update({"LayoutDirection": "LayoutDirection." + direction, "LayoutGap": gap,
                  "LayoutAlignItems": "LayoutAlignItems.Stretch",
                  "LayoutJustifyContent": "LayoutJustifyContent.Start",
                  "PaddingTop": pad, "PaddingBottom": pad, "PaddingLeft": pad, "PaddingRight": pad})
        if scroll:
            p["LayoutOverflowY"] = "LayoutOverflow.Scroll"
    if visible is not None:
        p["Visible"] = visible
    if extra:
        p.update(extra)
    return Ctl(name, CONTAINER, p, kids, "AutoLayout" if auto else "ManualLayout")


def lbl(name, text, x, y, w, h, size=13, color="cInk", bold=False, semibold=False, align="Left",
        font=UI, fill=None, valign="Middle", wrap=None, visible=None, extra=None, onselect=None, pad=0):
    p = {"Text": text, "X": x, "Y": y, "Width": w, "Height": h, "Size": size, "Color": color,
         "Font": font, "Align": "Align." + align, "VerticalAlign": "VerticalAlign." + valign,
         "PaddingLeft": pad, "PaddingRight": pad, "PaddingTop": 0, "PaddingBottom": 0,
         "FontWeight": "FontWeight.Bold" if bold else ("FontWeight.Semibold" if semibold else "FontWeight.Normal")}
    if fill:
        p["Fill"] = fill
    if wrap is not None:
        p["Wrap"] = wrap
    if visible is not None:
        p["Visible"] = visible
    if onselect:
        p["OnSelect"] = onselect
    if extra:
        p.update(extra)
    return Ctl(name, LABEL, p)


def rect(name, x, y, w, h, fill, visible=None, extra=None):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "Fill": fill, "BorderColor": fill}
    if visible is not None:
        p["Visible"] = visible
    if extra:
        p.update(extra)
    return Ctl(name, RECT, p)


def btn(name, text, x, y, w, h, onselect, kind="primary", visible=None, disabled=None, size=11, extra=None):
    if kind == "primary":
        fill, color, border, hover = "cJcb", "cOnJcb", "cJcb", "cJcbDark"
    elif kind == "danger":
        fill, color, border, hover = "RGBA(0,0,0,0)", "cStop", "cStop", "RGBA(220,115,97,0.15)"
    else:
        fill, color, border, hover = "cPanel2", "cInk", "cLine2", "cLine"
    p = {"Text": text, "X": x, "Y": y, "Width": w, "Height": h, "OnSelect": onselect,
         "Fill": fill, "Color": color, "BorderColor": border, "BorderThickness": 1,
         "HoverFill": hover, "HoverColor": color, "HoverBorderColor": border,
         "PressedFill": hover, "PressedColor": color, "PressedBorderColor": border,
         "DisabledFill": "cPanel", "DisabledColor": "cInk3", "DisabledBorderColor": "cLine",
         "RadiusTopLeft": 2, "RadiusTopRight": 2, "RadiusBottomLeft": 2, "RadiusBottomRight": 2,
         "Size": size, "FontWeight": "FontWeight.Semibold", "Font": UI,
         "PaddingLeft": 6, "PaddingRight": 6}
    if visible is not None:
        p["Visible"] = visible
    if disabled is not None:
        p["DisplayMode"] = "If(%s, DisplayMode.Disabled, DisplayMode.Edit)" % disabled
    if extra:
        p.update(extra)
    return Ctl(name, BUTTON, p)


def inp(name, x, y, w, h, default='""', hint="", mode=None, number=False, visible=None, extra=None,
        size=12, font=UI, onchange=None, disabled=None):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "Default": default, "HintText": q(hint),
         "Fill": "cSunk", "Color": "cInk", "BorderColor": "cLine2", "HoverBorderColor": "cInk3",
         "FocusedBorderColor": "cJcb", "HoverFill": "cSunk", "BorderThickness": 1,
         "Size": size, "Font": font, "PaddingLeft": 10, "PaddingRight": 6,
         "RadiusTopLeft": 0, "RadiusTopRight": 0, "RadiusBottomLeft": 0, "RadiusBottomRight": 0,
         "DisabledFill": "cPanel", "DisabledColor": "cInk2", "DisabledBorderColor": "cLine"}
    if mode == "multi":
        p["Mode"] = "TextMode.MultiLine"
    if number:
        p["Format"] = "TextFormat.Number"
    if visible is not None:
        p["Visible"] = visible
    if onchange:
        p["OnChange"] = onchange
    if disabled is not None:
        p["DisplayMode"] = "If(%s, DisplayMode.Disabled, DisplayMode.Edit)" % disabled
    if extra:
        p.update(extra)
    return Ctl(name, TEXTINPUT, p)


def dd(name, x, y, w, h, items, default=None, visible=None, extra=None, onchange=None):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "Items": items,
         "Fill": "cSunk", "Color": "cInk", "BorderColor": "cLine2", "BorderThickness": 1,
         "HoverFill": "cPanel2", "HoverColor": "cInk", "PressedFill": "cPanel2", "PressedColor": "cInk",
         "SelectionFill": "cJcb", "SelectionColor": "cOnJcb",
         "ChevronBackground": "cSunk", "ChevronFill": "cInk2",
         "ChevronHoverBackground": "cPanel2", "ChevronHoverFill": "cJcb",
         "Size": 12, "Font": UI, "PaddingLeft": 10,
         "RadiusTopLeft": 0, "RadiusTopRight": 0, "RadiusBottomLeft": 0, "RadiusBottomRight": 0}
    if default is not None:
        p["Default"] = default
    if visible is not None:
        p["Visible"] = visible
    if onchange:
        p["OnChange"] = onchange
    if extra:
        p.update(extra)
    return Ctl(name, DROPDOWN, p)


def date(name, x, y, w, h, default="Today()", visible=None, extra=None):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "DefaultDate": default, "Format": q("dd-mmm-yyyy"),
         "Fill": "cSunk", "Color": "cInk", "BorderColor": "cLine2", "BorderThickness": 1,
         "IconBackground": "cPanel2", "IconFill": "cJcb",
         "CalendarHeaderFill": "cJcb", "Size": 12, "Font": UI, "PaddingLeft": 10,
         "IsEditable": "false", "StartYear": 2020, "EndYear": 2040,
         "RadiusTopLeft": 0, "RadiusTopRight": 0, "RadiusBottomLeft": 0, "RadiusBottomRight": 0}
    if visible is not None:
        p["Visible"] = visible
    if extra:
        p.update(extra)
    return Ctl(name, DATEPICKER, p)


def gallery(name, x, y, w, h, items, row_h, kids, fill="RGBA(0,0,0,0)", visible=None, onselect=None,
            selected_fill=None, extra=None):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "Items": items, "TemplateSize": row_h,
         "TemplatePadding": 0, "ShowScrollbar": "true", "Fill": fill, "BorderColor": "cLine",
         "BorderThickness": 0}
    if selected_fill:
        p["TemplateFill"] = selected_fill
    if visible is not None:
        p["Visible"] = visible
    if onselect:
        p["OnSelect"] = onselect
    if extra:
        p.update(extra)
    return Ctl(name, GALLERY, p, kids, GALLERY_VARIANT)


def img(name, x, y, w, h, image, visible=None, extra=None):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "Image": image, "ImagePosition": "ImagePosition.Fit",
         "BorderColor": "RGBA(0,0,0,0)"}
    if visible is not None:
        p["Visible"] = visible
    if extra:
        p.update(extra)
    return Ctl(name, IMAGE, p)


def icon(name, x, y, w, h, ico, color="cInk2", onselect=None, visible=None, tooltip=None, pad=8):
    p = {"X": x, "Y": y, "Width": w, "Height": h, "Icon": "Icon." + ico, "Color": color,
         "PaddingTop": pad, "PaddingBottom": pad, "PaddingLeft": pad, "PaddingRight": pad}
    if onselect:
        p["OnSelect"] = onselect
    if visible is not None:
        p["Visible"] = visible
    if tooltip:
        p["Tooltip"] = q(tooltip)
        p["AccessibleLabel"] = q(tooltip)
    return Ctl(name, ICON, p)


def pill(name, x, y, w, status, h=22, visible=None):
    """Status pill exactly like the HTA's .pill: outlined, small caps-ish text."""
    col = "Coalesce(LookUp(nfPill, K = Upper(%s)).C, cInk3)" % status
    return lbl(name, "Upper(%s)" % status, x, y, w, h, size=8, color=col, semibold=True, align="Center",
               font=MONO, visible=visible,
               extra={"BorderColor": col, "BorderThickness": 1, "Fill": "RGBA(0,0,0,0)", "Wrap": "false"})
